apiVersion: apps/v1
kind: Deployment
metadata:
  name: timetable-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timetable-backend
  template:
    metadata:
      labels:
        app: timetable-backend
    spec:
      containers:
        - name: backend
          image: pawanyaduveer/timetable-backend
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: timetable-backend-service
spec:
  selector:
    app: timetable-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
