apiVersion: apps/v1
kind: Deployment
metadata:
  name: timetable-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timetable-frontend
  template:
    metadata:
      labels:
        app: timetable-frontend
    spec:
      containers:
        - name: timetable-frontend
          image: pawanyaduveer/timetable-frontend:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: timetable-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: timetable-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
